AllCops:
  Include:
    - '**/Rakefile'
    - '**/config.ru'
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - !ruby/regexp /old_and_unused\.rb$/
    - 'bin/*'

# other configuration
Metrics/LineLength:
  Max: 100

Style/Documentation:
  Enabled: false
